{
 "title": "MSK Metrics",
 "description": "Dashboard for metrics jmx_exporter protmetheus",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_controller_ControllerStats_Count, job)"
    }
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_server_BrokerTopicMetrics_Count{job=\"$job\"},instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_cluster_Partition_Value{job=\"$job\"}, topic)"
    }
   },
   {
    "name": "online_broker",
    "query": {
     "query": "query_result(count(up{job=~\"$job\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(job) (kafka_server_ReplicaManager_Value{job=\"$job\", name=\"LeaderCount\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(kafka_controller_KafkaController_Value{job=\"$job\",name=\"ActiveControllerCount\"})"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (kafka_controller_KafkaController_Value{job=\"$job\",name=\"GlobalTopicCount\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (kafka_server_ReplicaManager_Value{job=\"$job\",name=\"UnderReplicatedPartitions\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (kafka_server_ReplicaManager_Value{job=\"$job\",name=\"PartitionCount\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (kafka_server_ReplicaManager_Value{job=\"$job\",name=\"OfflineReplicaCount\"})"
    }
   ]
  },
  {
   "title": "Controller and Followers ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"ActiveControllerCount\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Partitions Leader and Replica Per Broker",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "count by(name) (kafka_server_ReplicaManager_Value{name=\"LeaderCount\", job=~\"$job\"}) / sum by(name) (kafka_server_ReplicaManager_Value{name=\"PartitionCount\", job=\"$job\"}) * 100"
    },
    {
     "expr": "count by(name) (kafka_server_ReplicaManager_Value{name=\"LeaderCount\", job=~\"$job\"})"
    },
    {
     "expr": "count by(instance) (kafka_cluster_Partition_Value{name=\"ReplicasCount\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Network Processor Avg Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kafka_network_SocketServer_Value{name=\"NetworkProcessorAvgIdlePercent\", job=~\"$job\", instance=~\"$broker\"} * 100)"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(request) (quantile(0.99, kafka_network_RequestMetrics_Count{name=\"TotalTimeMs\", request=\"Produce\", job=~\"$job\", instance=~\"$broker\"}))",
     "legendFormat": "Total Time"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(request) (quantile(0.99, kafka_network_RequestMetrics_Count{name=\"TotalTimeMs\", request=\"FetchConsumer\", job=~\"$job\", instance=~\"$broker\"}))",
     "legendFormat": "Total Time"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(request) (quantile(0.99, kafka_network_RequestMetrics_Count{name=\"TotalTimeMs\", request=\"FetchFollower\", job=~\"$job\", instance=~\"$broker\"}))",
     "legendFormat": "Total Time"
    }
   ]
  },
  {
   "title": "Produce Latency 99th per Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(request) (quantile(0.99, kafka_network_RequestMetrics_Count{name=\"TotalTimeMs\", request=\"Produce\", job=~\"$job\", instance=~\"$broker\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Latency 99th per Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(request) (quantile(0.99, kafka_network_RequestMetrics_Count{name=\"TotalTimeMs\", request=\"FetchConsumer\", job=~\"$job\", instance=~\"$broker\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FetchFollow Latency 99th per Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(request) (quantile(0.99, kafka_network_RequestMetrics_Count{name=\"TotalTimeMs\", request=\"FetchFollower\", job=~\"$job\", instance=~\"$broker\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sort(sum by(topic) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"MessagesInPerSec\", job=~\"$job\", topic=~\"$topic\", instance=~\"$broker\"}[5m])))",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort(sum by(topic) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"BytesInPerSec\", job=~\"$job\", topic=~\"$topic\", instance=~\"$broker\"}[5m])))",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Produce Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sort(sum by(instance) (irate(kafka_network_RequestMetrics_Count{request=~\"Produce\", job=~\"$job\", instance=~\"$broker\"}[5m])))",
     "legendFormat": "Request: {{instance}}"
    }
   ]
  },
  {
   "title": "Total Produce Request Rate Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(topic) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"TotalProduceRequestsPerSec\", job=~\"$job\", topic=~\"$topic\", instance=~\"$broker\"}[5m]))",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort(sum by(topic) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"BytesOutPerSec\", job=~\"$job\", topic=~\"$topic\", instance=~\"$broker\"}[5m])))",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"BytesOutPerSec\", job=~\"$job\", topic=~\"$topic\", instance=~\"$broker\"}[5m]))",
     "legendFormat": "Bytes Out [{{instance}}]"
    },
    {
     "expr": "sum by(instance) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"BytesInPerSec\", job=~\"$job\", topic=~\"$topic\", instance=~\"$broker\"}[5m]))",
     "legendFormat": "Bytes In [{{instance}}]"
    }
   ]
  },
  { "title": "Troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Failed Produce Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"FailedFetchRequestsPerSec\", job=~\"$job\", instance=~\"$broker\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"FailedProduceRequestsPerSec\", job=~\"$job\", instance=~\"$broker\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Produce Request Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(topic) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"FailedProduceRequestsPerSec\", job=~\"$job\", topic=~\"$topic\",instance=~\"$broker\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(topic) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"FailedFetchRequestsPerSec\", job=~\"$job\", topic=~\"$topic\",instance=~\"$broker\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Disconnects Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_server_SessionExpireListener_Count{job=~\"$job\", name=~\"ZooKeeperDisconnectsPerSec\", instance=~\"$broker\"}[1m]))",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Expires Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_server_SessionExpireListener_Count{job=~\"$job\", name=~\"ZooKeeperExpiresPerSec\", instance=~\"$broker\"}[1m]))",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Request Latency Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_server_ZooKeeperClientMetrics_Count{job=~\"$job\", name=~\"ZooKeeperRequestLatencyMs\", instance=~\"$broker\"})",
     "legendFormat": "Broker: {{instance}}"
    }
   ]
  },
  {
   "title": "Isr Shrinks / Isr Expands Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_server_ReplicaManager_Count{job=~\"$job\", name=~\"IsrShrinksPerSec\", instance=~\"$broker\"}[1m]))",
     "legendFormat": "ISR Shrinks Per Sec"
    },
    {
     "expr": "sum by(instance) (irate(kafka_server_ReplicaManager_Count{job=~\"$job\", name=~\"IsrExpandsPerSec\", instance=~\"$broker\"}[1m]))",
     "legendFormat": "ISR Expands Per Sec"
    }
   ]
  },
  {
   "title": "FetchFollower Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_network_RequestMetrics_Count{request=~\"FetchFollower\", job=~\"$job\"}[5m]))",
     "legendFormat": "Request: {{instance}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_network_RequestMetrics_Count{request=~\"FetchConsumer\", job=~\"$job\"}[5m]))",
     "legendFormat": "Request: {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Fetch Purgatory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_server_DelayedOperationPurgatory_Value{delayedOperation=~\"Fetch\", job=~\"$job\", instance=~\"$broker\"})",
     "legendFormat": "Broker {{instance}}"
    }
   ]
  },
  {
   "title": "Total Fetch Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_server_BrokerTopicMetrics_Count{job=~\"$job\", name=~\"TotalFetchRequestsPerSec\", instance=~\"$broker\"}[1m]))",
     "legendFormat": "Broker: {{instance}}"
    }
   ]
  },
  {
   "title": "Log Flush Stats Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (irate(kafka_log_logflushstats_logflushrateandtimems_count{job=\"$job\",instance=~\"$broker\"}[5m]))by(instance)",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Producer Purgatory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_server_DelayedOperationPurgatory_Value{job=~\"$job\", name=~\"NumDelayedOperations\", delayedOperation=~\"Produce\", instance=~\"$broker\"})",
     "legendFormat": "Broker {{instance}}"
    }
   ]
  },
  {
   "title": "Leader Election Rate Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_controller_ControllerStats_Count{name=\"LeaderElectionRateAndTimeMs\", job=~\"$job\", instance=~\"$broker\"}[1m]))",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "Partitions Leader Per Broker",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 124 },
   "targets": [
    {
     "expr": "count by(instance) (kafka_cluster_Partition_Value{name=\"ReplicasCount\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Disk Usage Segment Size",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 133 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sort(sum by(instance) (kafka_log_Log_Value{name=\"Size\", job=~\"$job\"}))",
     "legendFormat": "Instance Broker:  {{instance}}"
    }
   ]
  },
  {
   "title": "Count Partition per Broker",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 141 },
   "targets": [
    {
     "expr": "sort(sum by(instance) (kafka_server_ReplicaManager_Value{name=\"PartitionCount\", job=~\"$job\"}))",
     "legendFormat": "Instance Broker: {{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(java_lang_Memory_HeapMemoryUsage_used{job=\"$job\",instance=~\"$broker\"} )",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 } },
  {
   "title": "JVM Threads Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (java_lang_Memory_Verbose{job=~\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"$job\",instance=~\"$broker\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"node\"}[5m])",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  }
 ]
}