{
 "title": "Kubernetes / Compute Resources / Pod - Anomaly",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "CPU Anomaly Detection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\", cluster=\"$cluster\", container!=\"\"}) by (container)",
     "legendFormat": "Current CPU"
    },
    {
     "expr": "round(avg_over_time(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}[5m])[1h:1m]) + 2 * stddev_over_time(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])[1h:1m]),0.01)",
     "legendFormat": "1H Anomaly Threshold"
    },
    {
     "expr": "round(avg_over_time(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}[5m])[1d:1m]) + 2 * stddev_over_time(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])[1d:1m]),0.01)",
     "legendFormat": "1D Anomaly Threshold"
    }
   ]
  },
  {
   "title": "Memory Anomaly Detection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "Current Memory (MB)"
    },
    {
     "expr": "sum(((avg_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}[1h:1m]) ) + ((2 * stddev_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}[1h:1m]))))) by (pod)",
     "legendFormat": "1H Anomaly Threshold (MB)"
    },
    {
     "expr": "sum(((avg_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}[1d:1m])) + ((2 * stddev_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}[1d:1m]))))) by (pod)",
     "legendFormat": "1D Anomaly Threshold (MB)"
    }
   ]
  },
  {
   "title": "Network Receive Anomaly Detection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Current Receive (kbps)"
    },
    {
     "expr": "sum(((avg_over_time(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[5m])[1h:1m])) + (2 * stddev_over_time(irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])[1h:1m])))) by (pod)",
     "legendFormat": "1H Anomaly Threshold (kbps)"
    },
    {
     "expr": "sum(((avg_over_time(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}[5m])[1d:1m])) + (2 * stddev_over_time(irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])[1d:1m])))) by (pod)",
     "legendFormat": "1D Anomaly Threshold (kbps)"
    }
   ]
  },
  {
   "title": "Network Transmit Anomaly Detection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Current Transmit (kbps)"
    },
    {
     "expr": "sum(((avg_over_time(rate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\",namespace=\"$namespace\", pod=\"$pod\"}[5m])[1h:1m])) + (2 * stddev_over_time(rate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\",namespace=\"$namespace\", pod=\"$pod\"}[5m])[1h:1m])))) by (pod)",
     "legendFormat": "1H Anomaly Threshold (kbps)"
    },
    {
     "expr": "sum(((avg_over_time(rate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\",namespace=\"$namespace\", pod=\"$pod\"}[5m])[1d:1m])) + (2 * stddev_over_time(rate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\",namespace=\"$namespace\", pod=\"$pod\"}[5m])[1d:1m])))) by (pod)",
     "legendFormat": "1D Anomaly Threshold (kbps)"
    }
   ]
  }
 ]
}